# Generated by Django 4.1.5 on 2023-01-07 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home_Model_buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addes', models.CharField(max_length=200)),
                ('LenHome', models.IntegerField()),
                ('Floor', models.IntegerField()),
                ('Price', models.IntegerField()),
                ('kabinet', models.BooleanField()),
                ('Elevator', models.BooleanField()),
                ('Parking', models.BooleanField()),
                ('Img_main', models.ImageField(upload_to='media/')),
                ('Img_1', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('Img_2', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('Img_3', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('yournum', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Home_Model_Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addes', models.CharField(max_length=200)),
                ('LenHome', models.IntegerField()),
                ('Floor', models.IntegerField()),
                ('Price_First', models.IntegerField()),
                ('Price_month', models.IntegerField()),
                ('kabinet', models.BooleanField()),
                ('Elevator', models.BooleanField()),
                ('Parking', models.BooleanField()),
                ('Img_main', models.ImageField(upload_to='media/')),
                ('Img_1', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('Img_2', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('Img_3', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('yournum', models.CharField(max_length=100)),
            ],
        ),
    ]
